### PR TITLE
TE-10478 Added Propel release compatibility

### PR DESCRIPTION
**Pull request by dmytro-dymarchuk**
- Developer(s): @dmytro-dymarchuk

- Ticket: https://spryker.atlassian.net/browse/TE-10478

- Academy PR: ACADEMY_URL_HERE

- Release Group: https://release.spryker.com/release-groups/view/4239

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   UuidBehavior        | minor                 |                       |

-----------------------------------------

##### Change log

Improvements

- Moved template files.
- Updated @spryker/propel-orm dependency.

### CODE REVIEW

**Comment by dereuromark** [comment]
Please see other open pr

**Comment by dereuromark** [comment]
Which one is correct?

**Comment by dmytro-dymarchuk** [comment]
> Which one is correct?

I don't know whether we need to keep the same structure of directories but my variant is checked by https://github.com/spryker/suite-nonsplit/pull/6548?

**Comment by dereuromark** [comment]
Ok, then lets use yours,  but please also move the other changes over

**Comment by dmytro-dymarchuk** [comment]
Ok

**Review by dereuromark — APPROVED** [review]

**Comment by dereuromark** [comment]
We need to do a minor release here with a constraint towards our new release of propel module.

**Review by dereuromark — APPROVED** [review]

**Review by gechetspr — APPROVED** [review]

**Pull request merged**
